-- MySQL Script generated by MySQL Workbench
-- Sa 24 Nov 2018 23:17:28 CET
-- Model: wishlist model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wishlist_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wishlist_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wishlist_db` DEFAULT CHARACTER SET utf8 ;
USE `wishlist_db` ;

-- -----------------------------------------------------
-- Table `wishlist_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishlist_db`.`user` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uName` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlist_db`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishlist_db`.`wishlist` (
  `id_wishlist` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id_wishlist`),
  UNIQUE INDEX `id_wishlist_UNIQUE` (`id_wishlist` ASC),
  INDEX `fk_wshlst_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_wshlst_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `wishlist_db`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlist_db`.`wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wishlist_db`.`wish` (
  `id_wish` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_wishlist` INT UNSIGNED NOT NULL,
  `url` VARCHAR(512) NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `reserved` TINYINT(1) NOT NULL DEFAULT 0,
  `reserved_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id_wish`),
  INDEX `fk_wsh_wshlst_idx` (`id_wishlist` ASC),
  CONSTRAINT `fk_wsh_wshlst`
    FOREIGN KEY (`id_wishlist`)
    REFERENCES `wishlist_db`.`wishlist` (`id_wishlist`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
