# Generated by Django 2.2.6 on 2019-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='reservation_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='reserved_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
