# Generated by Django 2.2.6 on 2019-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0002_auto_20191226_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wish',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wish',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wish',
            name='reservation_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
    ]
